### ISSUE TITLE
Problem backing up large user folders

### ISSUE THREAD

**Issue by benneti** [YunoHost-Apps/borg_ynh#103]
Hi, 
after some searching I believe that for some reason my user folders cannot be backed up by borg (anymore).
I think all app backups and so on work without a problem (based on listing the backups) but the last backup of my user directory is from 2021-06-25 (when the backups still were not prefixed with a "_").
I am not sure why but it could be that the problem is related to one of the user directories being rather large.

My borg emails begin with
```
Creating a backup archive from the collected files...
The archive will contain about 340.5KiB of data.
Backup created
name: auto_conf
results: 
  apps: 
  system: 
    conf_ldap: Success
    conf_manually_modified_files: Success
    conf_ynh_certs: Success
    conf_ynh_settings: Success
size: 348708
Creating a backup archive from the collected files...
The archive will contain about 16.8GiB of data.
The operation 'Create a backup archive' could not be completed. Please share the full log of this operation using the command 'yunohost log share 20210921-210443-backup_create' to get help
Collecting files to be backed up for borg...
Loading installation settings...
Declaring files to be backed up...
Backup script completed for borg. (YunoHost will then actually copy those files to the archive).
Creating a backup archive from the collected files...
The archive will contain about 111.1KiB of data.
Backup created
name: auto_borg
results: 
  apps: 
    borg: Success
  system: 
size: 113773
```
for the full log see here https://paste.yunohost.org/raw/gefipadini for the full log in particular
```
2021-09-22 01:46:05,053: DEBUG - ++ date +%Y-%m-%d_%H:%M:%S
2021-09-22 01:46:05,067: DEBUG - + sed -e 's/^/[2021-09-22_01:46:05] /'
2021-09-22 07:34:01,690: ERROR - Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
Traceback (most recent call last):
  File "/usr/lib/moulinette/yunohost/hook.py", line 307, in hook_callback
    path, args=hook_args, chdir=chdir, env=env, raise_on_error=True
  File "/usr/lib/moulinette/yunohost/hook.py", line 393, in hook_exec
    raise YunohostError("hook_exec_failed", path=path)
yunohost.utils.error.YunohostError: Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
```

Additionally at the end I get a lot of 
```
Failed to format translated string 'backup_method_custom_finished': 'Custom backup method '{method}' finished' with arguments '()' and '{}, raising error: KeyError('method') (don't panic this is just a warning)
Failed to format translatable string 'backup_method_custom_finished': 'Custom backup method '{method}' finished' with arguments '()' and '{}', raising  error: KeyError('method') (don't panic this is just a warning)
Failed to format translated string 'backup_applying_method_custom': 'Calling the custom backup method '{method}'...' with arguments '()' and '{}, raising error: KeyError('method') (don't panic this is just a warning)
Failed to format translatable string 'backup_applying_method_custom': 'Calling the custom backup method '{method}'...' with arguments '()' and '{}', raising  error: KeyError('method') (don't panic this is just a warning)
```
warnings but I am not sure whether they are related.

**Comment by fflorent** [comment]
Hi there,

Sorry, it has been 5 years and nobody could provide you suggestion. The link to the detailed logs is dead.

I hope you found a solution in the meantime.

I am closing. Feel free to open another issue if you still encounter issues with the app.
