### ISSUE TITLE
Folder already exists: '/home/yunohost.backup/tmp/***'

### ISSUE THREAD

**Issue by klorydryk** [YunoHost-Apps/borg_ynh#51]
I tried to manually start a backup via `sudo systemctl start borg.service`

I got the log in real time with `sudo journalctl -fu borg.service`

It failed with :
```
   filesystem.mkdir(self.work_dir, 0o750, parents=True, uid='admin')
File "/usr/lib/python2.7/dist-packages/moulinette/utils/filesystem.py", line 273, in mkdir
   raise OSError(errno.EEXIST, m18n.g("folder_exists", path=path))
OSError: [Errno 17] Folder already exists: '/home/yunohost.backup/tmp/auto_data'
Collecting files to be backed up for borg...
Creating a backup archive from the collected files...
Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
Custom backup method could not get past the 'backup' step
Collecting files to be backed up for borgserver...
Creating a backup archive from the collected files...
Could not run script: /etc/yunohost/hooks.d/backup_method/05-borg_app
Custom backup method could not get past the 'backup' step
Traceback (most recent call last):
  File "/usr/bin/yunohost", line 218, in <module>
  timeout=opts.timeout,
  File "/usr/lib/python2.7/dist-packages/moulinette/__init__.py", line 149, in cli
   moulinette.run(args, output_as=output_as, password=password, timeout=timeout)
 File "/usr/lib/python2.7/dist-packages/moulinette/interfaces/cli.py", line 469, in run
   ret = self.actionsmap.process(args, timeout=timeout)
  File "/usr/lib/python2.7/dist-packages/moulinette/actionsmap.py", line 588, in process
    return func(**arguments)
   File "/usr/lib/moulinette/yunohost/backup.py", line 2172, in backup_create
   backup_manager = BackupManager(name, description)
  File "/usr/lib/moulinette/yunohost/backup.py", line 277, in __init__
   self._init_work_dir()
 File "/usr/lib/moulinette/yunohost/backup.py", line 348, in _init_work_dir
    filesystem.mkdir(self.work_dir, 0o750, parents=True, uid='admin')
  File "/usr/lib/python2.7/dist-packages/moulinette/utils/filesystem.py", line 273, in mkdir
    raise OSError(errno.EEXIST, m18n.g("folder_exists", path=path))
 OSError: [Errno 17] Folder already exists: '/home/yunohost.backup/tmp/auto_dokuwiki'
```
followed by the same for all installed applications.
I tried to do a normal Yunohost backup and it works, so I don't understand why it fails with Borg app.

Thanks!

**Comment by fflorent** [comment]
Hi there,

Is this still an issue nowadays?
